name: "Test PR Milestone Check"

on:
  pull_request:
    types: [opened]

  issues:
    types: [opened, milestoned, demilestoned]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        uses: ./
